/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

// Code generated by update-protocol-version.ts. DO NOT EDIT.

/**
 * The maximum SDK protocol version supported.
 * This must match the version expected by the copilot-agent-runtime server.
 */
export const SDK_PROTOCOL_VERSION = 3;

/**
 * The minimum SDK protocol version supported.
 * Servers reporting a version in [MIN, MAX] are considered compatible.
 */
export const MIN_SDK_PROTOCOL_VERSION = 2;

/**
 * Gets the SDK protocol version (maximum supported).
 * @returns The protocol version number
 */
export function getSdkProtocolVersion(): number {
    return SDK_PROTOCOL_VERSION;
}

/**
 * Gets the minimum SDK protocol version supported.
 * @returns The minimum protocol version number
 */
export function getMinSdkProtocolVersion(): number {
    return MIN_SDK_PROTOCOL_VERSION;
}
