// Code generated by update-protocol-version.ts. DO NOT EDIT.

namespace GitHub.Copilot.SDK;

/// <summary>
/// Provides the SDK protocol version.
/// This must match the version expected by the copilot-agent-runtime server.
/// </summary>
internal static class SdkProtocolVersion
{
    /// <summary>
    /// The maximum SDK protocol version supported.
    /// </summary>
    private const int Version = 3;

    /// <summary>
    /// The minimum SDK protocol version supported.
    /// Servers reporting a version in [Min, Max] are considered compatible.
    /// </summary>
    private const int MinVersion = 2;

    /// <summary>
    /// Gets the SDK protocol version (maximum supported).
    /// </summary>
    public static int GetVersion() => Version;

    /// <summary>
    /// Gets the minimum SDK protocol version supported.
    /// </summary>
    public static int GetMinVersion() => MinVersion;
}
